# Generated by Django 4.2.6 on 2023-10-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineApp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
