# Generated by Django 4.2.6 on 2023-10-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineApp', '0004_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
