# Generated by Django 4.2.6 on 2023-10-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineApp', '0006_myuser_enrolled_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
