# Generated by Django 4.2.6 on 2023-10-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('onlineApp', '0008_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(related_name='my_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='my_users', to='auth.permission'),
        ),
    ]
